extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    # default + `post` for blog post
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - post
      - refactor
      - revert
      - style
      - test
