# Default state for all rules
default: true
# Path to configuration file to extend
extends: null

# first-heading-h1
# First heading should be a `level: int` heading
MD002: false

# heading-style
MD003:
  style: 'atx'

# ul-style
MD004:
  style: 'dash'

# no-trailing-spaces
MD009:
  # Include unnecessary breaks
  strict: true
  # > You must set to a value >= 2 to take effect
  br_spaces: null
  # Allow spaces for empty lines in list items
  list_item_empty_lines: false

# no-hard-tabs
MD010:
  # Include code blocks
  code_blocks: true
  spaces_per_tab: 2

# line-length
MD013:
  strict: false
  stern: false

  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100

  # Include ...
  code_blocks: true
  tables: true
  headings: true
  headers: true

# no-missing-space-closed-atx
# No space inside hashes on closed atx style heading
MD020: false

# no-multiple-space-closed-atx
# Multiple spaces inside hashes on closed atx style heading
MD021: false

# blanks-around-headings
MD022:
  lines_above: 1
  lines_below: 1

# no-trailing-punctuation
MD026:
  punctuation: ',.;:、。，．；：'

# ol-prefix
MD029:
  style: 'one'

# blanks-around-fences
# Fenced code blocks should be surrounded by blank lines
MD031:
  # Include list items
  list_items: false

# no-inline-html
MD033:
  allowed_elements: ['img']

# hr-style
MD035:
  style: '---'

# no-emphasis-as-heading
# It won't fire on emphasis used within regular text,
# multi-line emphasized paragraphs, or paragraphs ending in <punctuation>.
MD036:
  punctuation: ',.;:、。，．；：'

# first-line-heading
MD041: false

# required-headings
# Required heading structure (default `null` for disabled)
MD043: false

# MD044/proper-names - Proper names should have the correct capitalization
MD044: false

# code-block-style
MD046:
  style: 'fenced'

# code-fence-style
MD048:
  style: 'backtick'
